/**
 * Editorial gate. Every supplementary object has a status: draft → researched → reviewed → approved → published.
 * Nothing generated by AI bypasses review: AI drafts are stored as 'draft'.
 *
 * NEXT_PUBLIC_MIN_EDITORIAL_STATUS controls what a build shows:
 *   'draft'     — editorial preview (default for this prototype; the app says so in Settings)
 *   'published' — production: only material that has passed review.
 */
import type { EditorialStatus } from './types';

export const STATUS_ORDER: EditorialStatus[] = ['draft', 'researched', 'reviewed', 'approved', 'published'];
const ORDER = STATUS_ORDER;

export const MIN_STATUS: EditorialStatus = ((process.env.NEXT_PUBLIC_MIN_EDITORIAL_STATUS as EditorialStatus) || 'draft');

export const isEditorialPreview = MIN_STATUS === 'draft';

export function visibleByStatus<T extends { editorial?: { status: EditorialStatus } }>(items: T[], min: EditorialStatus = MIN_STATUS): T[] {
  const floor = ORDER.indexOf(min);
  return items.filter((i) => ORDER.indexOf(i.editorial?.status ?? 'draft') >= floor);
}

export const EVIDENCE_LABEL: Record<string, string> = {
  A: 'Explicit — Scripture states it',
  B: 'Direct textual connection',
  C: 'Objective correspondence',
  D: 'Interpretive',
};

export const LEVEL_LABEL: Record<number, string> = {
  1: 'Explicit quotation',
  2: 'Explicit fulfilment',
  3: 'Direct reference',
  4: 'Strong textual parallel',
};

export const LEVEL_NOTE: Record<number, string> = {
  1: 'The passage says it is quoting (“it is written”, “spoken by the prophet”) and the wording is shared.',
  2: 'The passage says a word was “fulfilled”, and the wording is shared.',
  3: 'The passage names a person, place or event of the other passage.',
  4: 'The two passages share a run of words. Scripture does not say that one quotes the other.',
};
