import { test } from '@playwright/test';
import { goToChapter, openAt, readPage, showChrome, turnUntilVisible } from './helpers';

// Generates docs/screenshots. Run with: SCREENSHOTS=1 npx playwright test screenshots
test.skip(!process.env.SCREENSHOTS, 'screenshots only on demand');

test('key screens', async ({ page }, info) => {
  test.setTimeout(300_000);
  const shot = async (name: string, wait = 900) => {
    await page.waitForTimeout(wait);
    await page.screenshot({ path: `docs/screenshots/${info.project.name}-${name}.jpg`, quality: 82 });
  };
  const esc = async () => {
    await page.keyboard.press('Escape');
    await page.waitForTimeout(700);
  };
  await page.goto('/');
  await shot('01-cover', 1400);
  await openAt(page, 'Gen.1');
  await shot('02-genesis-1', 900);
  await page.keyboard.press('c');
  await page.getByTestId('contents-book-Ps').click();
  await shot('03-contents-library', 700);
  await esc();
  await page.keyboard.press('/');
  await page.getByTestId('search-input').fill('"my shepherd"');
  await page.waitForTimeout(2500);
  await shot('04-search-phrase', 600);
  await page.getByTestId('search-verse').first().click();
  await page.waitForTimeout(900);
  await shot('05-psalm-23', 700);
  await page.getByTestId('verse-num-4').click();
  await page.getByTestId('highlight-gold').click();
  await shot('06-verse-tools', 700);
  await page.getByTestId('open-compare').click();
  await shot('07-compare-translations', 1800);
  await esc();
  await goToChapter(page, 'Matt.2');
  await turnUntilVisible(page, 'margin-connection-x-hosea11');
  await page.getByTestId('margin-connection-x-hosea11').click();
  await shot('08-vellum-prophet', 1400);
  await esc();
  await goToChapter(page, 'Matt.4');
  await page.locator('[data-testid^="margin-connection-m-Matt_4_4"]').first().click();
  await shot('09-vellum-level-1-found-by-wording', 1600);
  await esc();
  await page.getByTestId('verse-num-4').click();
  await page.getByTestId('open-words').click();
  await page.getByTestId('original-words').locator('li button').nth(3).click();
  await shot('10-greek-word-study', 1200);
  await esc();
  await goToChapter(page, 'Acts.13');
  await page.keyboard.press('m');
  await page.getByTestId('layer-paul-1').click();
  await page.getByTestId('map-next').click();
  await page.getByTestId('map-next').click();
  await shot('11-atlas-paul', 2600);
  await page.getByTestId('map-overview').click();
  await shot('12-atlas-overview', 2400);
  await esc();
  await page.keyboard.press('/');
  await page.getByTestId('search-input').fill('Emmaus');
  await page.getByTestId('search-place-emmaus').click({ timeout: 15000 });
  await shot('13-place-disputed', 1200);
  await esc();
  await page.keyboard.press('/');
  await page.getByTestId('search-input').fill('Abraham');
  await page.getByTestId('search-person-abraham').click({ timeout: 15000 });
  await shot('14-person-family', 1200);
  await esc();
  await goToChapter(page, 'Luke.3');
  await turnUntilVisible(page, 'insert-tab-insert-genealogy-luke-3', 4);
  await page.getByTestId('insert-tab-insert-genealogy-luke-3').click();
  await shot('15-genealogy-luke', 1500);
  await esc();
  await goToChapter(page, 'Gen.6');
  await turnUntilVisible(page, 'insert-tab-insert-scale-ark', 3);
  await page.getByTestId('insert-tab-insert-scale-ark').click();
  await shot('16-scale-ark', 1300);
  await esc();
  await showChrome(page);
  await page.getByTestId('open-timeline').click();
  await shot('17-timeline', 1800);
  await esc();
  await page.keyboard.press('t');
  await shot('18-thread', 1300);
  await esc();
  await readPage(page);
  await showChrome(page);
  await page.getByTestId('open-mine').click();
  await shot('19-your-bible', 900);
  await esc();
  await showChrome(page);
  await page.getByTestId('open-settings').click();
  await page.getByTestId('open-family').click();
  await shot('20-family', 900);
  await esc();
  await showChrome(page);
  await page.getByTestId('open-settings').click();
  await page.getByRole('radio', { name: 'Night' }).click();
  await page.getByRole('radio', { name: 'Verses' }).click();
  await esc();
  await goToChapter(page, 'Ps.23');
  await shot('21-night-verse-by-verse', 900);
  await page.keyboard.press('f');
  await shot('22-focus', 800);
});
